[package]
name = "steam-screenshot-importer"
version = "1.0.1"
description = "Steam Screenshot Importer"
authors = ["yobson"]
license = "GPL-3.0-only"
repository = "https://github.com/yobson1/steam-screenshot-importer"
readme = "README.md"
keywords = ["steam", "screenshots", "importer"]
categories = ["multimedia::images"]
default-run = "steam-screenshot-importer"
edition = "2024"

[features]
fps = ["dep:gpui-fps"]

[lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
multiple_crate_versions = "allow"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "1"
ureq = "3"
winresource = "0.1"

[dependencies]
anyhow = "1"
async-channel = "2.5"
bytemuck = { version = "1", features = ["derive"] }
cosmic-text = "0.19"
directories = "6.0"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["wayland", "x11"] }
image = { version = "0.25", features = ["avif-native"] }
log = "0.4"
pollster = "1.0"
rayon = "1.12"
reqwest = { version = "0.13", features = ["blocking", "json", "query"] }
rfd = "0.17"
rusqlite = { version = "0.40", features = ["bundled"] }
rust-embed = "8.12"
semver = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = "5.2"
steamlocate = "2.1"
steamy-vdf = "0.2"
steamworks = { version = "0.13", features = ["raw-bindings"] }
walkdir = "2.5"
wgpu = "29"
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
gpui-fps = { git = "https://github.com/longbridge/gpui-component", optional = true }

[dev-dependencies]
tempfile = "3"

[profile.dev]
debug = "limited"

[profile.dev.package]
cosmic-text = { opt-level = 3 }
gpui = { opt-level = 3 }
image = { opt-level = 3 }
resvg = { opt-level = 3 }
taffy = { opt-level = 3 }
wgpu = { opt-level = 3 }
