// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getGames: () => __TAURI_INVOKE<Game[]>("get_games"),
	getRecentSteamUser: () => __TAURI_INVOKE<string>("get_recent_steam_user"),
	importScreenshots: (filePaths: string[], appId: number, jpegQuality: number, filterType: string) => __TAURI_INVOKE<null>("import_screenshots", { filePaths, appId, jpegQuality, filterType }),
	pickScreenshotFiles: () => __TAURI_INVOKE<string[]>("pick_screenshot_files"),
};

/* Types */
export type Game = {
	appId: number,
	imageSrc: string,
	appName: string,
};

