name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    uses: ./.github/workflows/release-build-linux.yml
    with:
      version: ${{ github.ref_name }}
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  build-windows:
    uses: ./.github/workflows/release-build-windows.yml
    with:
      version: ${{ github.ref_name }}

  publish:
    needs:
      - build-linux
      - build-windows
    permissions:
      contents: write
    uses: ./.github/workflows/release-publish.yml
    secrets:
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
