name: Manual Windows Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/release-build-windows.yml
    with:
      artifact-name: steam-screenshot-importer-windows-x86_64
